# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Build

env:
  MODULE_VERSION: '0.1' # manually change major and minor build version of component here
  

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Build
      run: | 
        npm ci
        npm run build
        
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: dist/ezeep
        name: ezeep-js.zip
    
    - name: ZIP Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: 'dist/ezeep'
        path: '.'
        filename: 'ezeep-js.zip'
        
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: "${{ env.MODULE_VERSION }}.${{ github.run_number }}"
        prerelease: true
        artifacts: "dist/ezeep/ezeep-js.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
