# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Build

env:
  MODULE_VERSION: '0.1.${{ github.run_number }}'   # manually change major and minor build version of component here
  DIST_PATH: 'dist/ezeep'                          # deployment path
  ARTIFACT_NAME: 'ezeep-js.zip'                    # artifact name
  PRERELEASE: true                                 # true if marked as pre-release, false if production-ready

on:
  push:
    branches: [ main ]

jobs:
  build:

    environment: Production
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Build
      run: | 
        npm ci
        npm run build
        
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ${{ env.DIST_PATH }}
        name: ${{ env.ARTIFACT_NAME }}
    
    - name: ZIP Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: ${{ env.DIST_PATH }}
        path: '.'
        filename: ${{ env.ARTIFACT_NAME }}
        
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: "${{ env.MODULE_VERSION }}"
        prerelease: ${{ env.PRERELEASE }}
        artifacts: "${{ env.DIST_PATH }}/${{ env.ARTIFACT_NAME }}"
        token: ${{ secrets.GITHUB_TOKEN }}
